### ISSUE TITLE
Snow does not show through glass / glass pane

### ISSUE THREAD

**Issue by willownezz** [GiantLuigi4/FancySnowyWeather#1]
![2020-11-26_00 35 16](https://user-images.githubusercontent.com/3631656/100327108-ac1f0c00-2f7f-11eb-8b3b-857aa9e11a73.png)

Snow does not show through glass / glass pane

Modpack ATM6 1.3.2c
FancySnowyWeather 1.2

**Comment by willownezz** [comment]
Also is it supposed to snow in a Beach biome ? here is the temperature map (I am at the orange/red area

![2020-11-26_00 41 02](https://user-images.githubusercontent.com/3631656/100327439-264f9080-2f80-11eb-8e32-d11ebb28033c.png)

**Comment by GiantLuigi4** [comment]
So uh, for the not passing through glass, that’s how vanilla does it if I’m not mistaken, I copied vanilla’s code.

Also, yes it is meat to snow  in beaches. It can snow anywhere that is not a desert, or marked as no rain.

**Comment by GiantLuigi4** [comment]
So uh, for the not passing through glass, that’s how vanilla does it if I’m not mistaken, I copied vanilla’s code.

Also, yes it is meat to snow  in beaches. It can snow anywhere that is not a desert, or marked as no rain.

**Comment by GiantLuigi4** [comment]
Just tested for the issue of it not rendering through glass, it is infact a vanilla issue, which is not surprising to me.
Transparency is difficult to work with at best.
