### ISSUE TITLE
[1.16.4] SaveState Crash middle of server gameplay...

### ISSUE THREAD

**Issue by Cixon** [GiantLuigi4/FancySnowyWeather#2]
Logs:

[debug.log](https://github.com/GiantLuigi4/FancySnowyWeather/files/5766940/debug.log)

### **Line 978 - end**
[latest.log](https://github.com/GiantLuigi4/FancySnowyWeather/files/5766944/latest.log)

**Comment by GiantLuigi4** [comment]
Ok I'm sorry but, my first question is, how many mods do you have on???

Second of all, at the very end of the log it's "watchdog" which killed the server, and finally, I don't think that you're on the latest version of fancy snowy weathers considering all of the "1"s in console.

**Comment by Cixon** [comment]
> 
> 
> Ok I'm sorry but, my first question is, how many mods do you have on???
> 
> Second of all, at the very end of the log it's "watchdog" which killed the server, and finally, I don't think that you're on the latest version of fancy snowy weathers considering all of the "1"s in console.

I have a variety of mods but none of them aside from SereneSeasons and FancyWeather modifies weather stuff.
Also, I'm not sure if I am or not but I never had this issue before. Figured I'd report it anyways considering the amount of messages spammed in the console.

**Comment by GiantLuigi4** [comment]
yeah, I'm pretty sure I removed the console spam in the [latest](https://www.curseforge.com/minecraft/mc-mods/fancy-snowy-weather/files/3156659)

**Comment by GiantLuigi4** [comment]
Tbh, I wouldn't be surprised if the issue was the memory useage due to how many mods there are, and the fact that it was a watchdog kill.

Might also have just been an stupidly large amount of lag, or some mod wound up getting stuck in an infinite loop.
